//------------------------------------------------------------------------------
// <auto-generated>
//     Ręcznie przygotowana wersja zastępcza dla zasobów projektu.
//------------------------------------------------------------------------------

namespace PaintApplicationAssignment.Properties
{
    using System.Drawing;
    using System.IO;
    using System.Windows.Forms;

    internal static class Resources
    {
        private static Bitmap LoadBitmap(string fileName)
        {
            string baseDir = Application.StartupPath;
            string fullPath = Path.Combine(baseDir, "Resources", fileName);

            if (!File.Exists(fullPath))
            {
                return new Bitmap(1, 1);
            }

            using (var temp = new Bitmap(fullPath))
            {
                return new Bitmap(temp);
            }
        }

        internal static Bitmap icons8_file_24 => LoadBitmap("icons8-file-24.png");
        internal static Bitmap icons8_opened_folder_26 => LoadBitmap("icons8-opened-folder-26.png");
        internal static Bitmap icons8_broom_32 => LoadBitmap("icons8-broom-32.png");
        internal static Bitmap Save_32px => LoadBitmap("Save_32px.png");
        internal static Bitmap icons8_close_24 => LoadBitmap("icons8-close-24.png");
        internal static Bitmap Triangle_32px => LoadBitmap("Triangle_32px.png");
        internal static Bitmap Rectangle_Stroked_32px => LoadBitmap("Rectangle Stroked_32px.png");
        internal static Bitmap Circle_32px => LoadBitmap("Circle_32px.png");
        internal static Bitmap icons8_line_24 => LoadBitmap("icons8-line-24.png");
        internal static Bitmap Erase_32px => LoadBitmap("Erase_32px.png");
        internal static Bitmap icons8_fill_color_30 => LoadBitmap("icons8-fill-color-30.png");
        internal static Bitmap icons8_color_64 => LoadBitmap("icons8-color-64.png");
        internal static Bitmap Edit_32px => LoadBitmap("Edit_32px.png");
    }
}